### ISSUE TITLE
Test model MAP: AssertionError: No labels found in \data\coco\labels\train2017

### ISSUE THREAD

**Issue by danbader88** [CoCoPIE-Pruning/CoCoPIE-ModelZoo#6]
When I run the command-
`python test.py --img-size 320 --batch-size 64 --device 0 --cfg cfg/csdarknet53s-panet-spp.cfg --weights weights/best8x-514.pt --data data/coco2014.data`

I get the following error-
`AssertionError: No labels found in \CoCoPIE-ModelZoo\YOLObile\data\coco\labels\train2017\.`

My labels-
![label](https://user-images.githubusercontent.com/69597128/95590476-b898e500-0a63-11eb-8ee0-e9e4dacdadf3.JPG)

**Comment by nightsnack** [comment]
Move your /coco folder to CoCoPIE-ModelZoo folder and then check it again.

Follow the instructions on README.md
Download Coco Dataset: (18 GB)
`cd ../ && sh YOLObile/data/get_coco2014.sh`

**Comment by danbader88** [comment]
I followed the same but it does not solve the issue.
I am getting the following error-

`Traceback (most recent call last):
  File "test.py", line 263, in <module>
    opt.augment)
  File "test.py", line 59, in test
    names = load_classes(data['names'])  # class names
  File "D:\Projects\AI360\CoCoPIE-ModelZoo-master\YOLObile\utils\utils.py", line 58, in load_classes
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/coco.names'`

My project structure is now as below-
![1](https://user-images.githubusercontent.com/69597128/95715729-f5452600-0c87-11eb-83b1-2f74c884a826.JPG)

![2](https://user-images.githubusercontent.com/69597128/95715742-fa09da00-0c87-11eb-910a-028194611932.JPG)

![3](https://user-images.githubusercontent.com/69597128/95715757-ff672480-0c87-11eb-8f18-b9233320144e.JPG)

**Comment by nightsnack** [comment]
oh so this might be a issue with windows I ignored. I do not have windows environment. I suggest checking the coco2014.data file in /data and change the path inside to windows-friendly.

**Comment by danbader88** [comment]
Thanks @nightsnack . Indeed it was path issue related to windows. I corrected it in .data file and now able to successfully run the test file.

**Comment by MuhammadAsadJaved** [comment]
@danbader88  How were the results? is it the same?  + Have you tried to write codes for demo etc?

**Comment by dsbyprateekg** [comment]
@MuhammadAsadJaved I tested the mAP for coco 2017 dataset in my NVIDIA GeForce GTX 1060 system and achieved the following-
![f1](https://user-images.githubusercontent.com/30830541/96824371-3e496700-144c-11eb-81d2-0675ed384556.JPG)

![f2](https://user-images.githubusercontent.com/30830541/96824381-44d7de80-144c-11eb-9674-39404aae6150.JPG)

![f3](https://user-images.githubusercontent.com/30830541/96824386-4a352900-144c-11eb-825d-68ca2761fda0.JPG)

But I have not tested the same on any mobile device yet.

**Comment by MuhammadAsadJaved** [comment]
@dsbyprateekg   Thank you for the results.  Is there any suggestion to run the code for demo?

**Comment by dsbyprateekg** [comment]
@MuhammadAsadJaved You just need to follow author's README file and if you have windows machine then you need to adjust the path in .data file. It will run without any issue.

**Comment by MuhammadAsadJaved** [comment]
> @MuhammadAsadJaved You just need to follow author's README file and if you have windows machine then you need to adjust the path in .data file. It will run without any issue.

I am not talking about tests or comparisons. I am talking about checking the model on image/video inputs as a demo.
